"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j73yrt8#0*c7m&dqno$_4$6l%90r%bn03_blq02l*0fa9rbkvd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["https://django-atut-vidhan-ao0y.onrender.com", ".onrender.com", "atutvidhan.com", "localhost", '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'connect.apps.ConnectConfig',
    'user.apps.UserConfig',
    'siteadmin.apps.SiteadminConfig',
    'search.apps.SearchConfig',
    'plans.apps.PlansConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'user.context_processors.fallback_images',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [("127.0.0.1", 6379)],  # Make sure Redis is running
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASE_CONNECTION_URL = "postgresql://atut_vidhan_db_user:GTyahfgbc5I5rshSP7JIRbmh0iLkasE8@dpg-d272rnvdiees73bf9jo0-a.ohio-postgres.render.com/atut_vidhan_db"
DATABASE_CONNECTION_URL = "postgresql://django_atut_vidhan_db_user:HFmy25OIjwlujsitARjhujpIHBh9o7KF@dpg-d2s5j1vdiees739dl1ng-a.singapore-postgres.render.com/django_atut_vidhan_db"
DATABASES = {
    'default': dj_database_url.config(default=DATABASE_CONNECTION_URL)
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "main/static"]  # ✅ only existing dir
STATIC_ROOT = BASE_DIR / "staticfiles"  # ✅ where collectstatic dumps into

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
DEBUG = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'user.User'

LOGIN_URL = "auth/"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 465
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "atutvidhanmatrimony@gmail.com"  # 🔑 Your Gmail
EMAIL_HOST_PASSWORD = "htynyxqhcfpzapvt"  # 🔒 App password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

USE_L10N = False  # This disables locale-based formats so we can enforce our own

# Input: what users type in forms
DATE_INPUT_FORMATS = ['%d-%m-%Y']

# Output: how dates are displayed in forms or rendered
DATE_FORMAT = 'd-m-Y'

DEFAULT_FEMALE_FALLBACK_URL = "https://krtiayhjqgtsruzboour.supabase.co/storage/v1/object/public/media/profile_images/femaledefault.png"
DEFAULT_MALE_FALLBACK_URL = "https://krtiayhjqgtsruzboour.supabase.co/storage/v1/object/public/media/profile_images/maledefault.png"


ASGI_APPLICATION = "main.asgi.application"

# In-memory channel layer (for dev)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

ALLOWED_HOSTS = [
    "django-atut-vidhan-ao0y.onrender.com",
    "atutvidhan.com",   # if you’re using your custom domain
    ".onrender.com",    # wildcard for any other Render subdomains
    "localhost",
    "127.0.0.1",
]

CSRF_TRUSTED_ORIGINS = [
    "https://django-atut-vidhan-ao0y.onrender.com",
    "https://atutvidhan.com",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# These can help if cookies aren't sticking, but keep them True in production:
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
