# Generated by Django 5.2.1 on 2025-07-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_profile_caste_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
