# Generated by Django 5.2.1 on 2025-08-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_email_otp_user_otp_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], db_index=True, max_length=10, null=True),
        ),
    ]
