# Generated by Django 5.2.1 on 2025-09-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
    ]
