# Generated by Django 5.2.1 on 2025-09-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_remove_profile_image_remove_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.PositiveSmallIntegerField(db_index=True, default=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="looking_for",
            field=models.CharField(
                blank=True,
                choices=[("Bride", "Bride"), ("Groom", "Groom"), ("Other", "Other")],
                db_index=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[("Single", "Single"), ("Married", "Married")],
                db_index=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="religion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hindu", "Hindu"),
                    ("Muslim", "Muslim"),
                    ("Christian", "Christian"),
                    ("Sikh", "Sikh"),
                    ("Other", "Other"),
                ],
                db_index=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                db_index=True,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["full_name"], name="user_profil_full_na_b4a1b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["gender"], name="user_profil_gender_8a25b2_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["city"], name="user_profil_city_5ff50d_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["state"], name="user_profil_state_af361d_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["country"], name="user_profil_country_d7256b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["religion"], name="user_profil_religio_1b59b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["profession"], name="user_profil_profess_f9b81e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["looking_for"], name="user_profil_looking_99f3b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["age"], name="user_profil_age_021b83_idx"),
        ),
    ]
