# Generated by Django 5.2.1 on 2025-10-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_alter_profile_age_alter_profile_looking_for_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="looking_for",
            field=models.CharField(
                blank=True,
                choices=[("Bride", "Bride"), ("Groom", "Groom"), ("Other", "Other")],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[("Single", "Single"), ("Married", "Married")],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="religion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hindu", "Hindu"),
                    ("Muslim", "Muslim"),
                    ("Christian", "Christian"),
                    ("Sikh", "Sikh"),
                    ("Other", "Other"),
                ],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
    ]
