# Generated by Django 5.2.1 on 2025-08-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
