# Generated by Django 5.2.1 on 2025-09-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0002_chatmessage_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
